export declare enum ProtectionType {
    PAGE_NOACCESS,
    PAGE_READONLY,
    PAGE_READWRITE,
    PAGE_WRITECOPY,
    PAGE_EXECUTE,
    PAGE_EXECUTE_READ,
    PAGE_EXECUTE_READWRITE,
    PAGE_EXECUTE_WRITECOPY,
    PAGE_GUARD,
    PAGE_NOCACHE,
    PAGE_WRITECOMBINE,
    PAGE_ENCLAVE_THREAD_CONTROL,
    PAGE_TARGETS_NO_UPDATE,
    PAGE_TARGETS_INVALID,
    PAGE_ENCLAVE_UNVALIDATED
}